27.06.22

I've noticed that my Infura requests volume went through the roof over the weekend, I received emails stating that I had used 75% of my allocated volume, then the next day it was 100%. The weird part is that I received those emails the days I wasn't actively working on the project.
Either transactions take time to be updated on the Infura server, or there's something that I am not aware of.

I've deployed the contract once more, it went fine. Tried to fund my contract with WETH but I do not have enough ETH in my wallet. I've already used the faucets and still, it isn't enough. and Aave does not use rinkeby. I can't believe I'd get stuck on testing my scripts just because of that, there must be a workaround.
I tried reducing the MINIMUM_FLASHLOAN_WETH_BALANCE but it obviously failed. I got some WETH, but this WETH wasn't enough to cover the tx fees of calling the flashloan contract
https://faucets.chain.link/ this link gives enough ETH for me to try, also only once/24h.

I've tried several times, I have changed the amounts of minimum balance, I'm wondering if there's not a problem with the way the script grabs my account... cause I have enough WETH available to cover the 0.02ETH necessary... or am I f\*\*\* up again on the math?

I tried deleting my build folder + package-lock.json, recompile and run the scripts, but the same error went through.

I can't figure out what is going on, and needed a break, so I wrote my first test to check if my account was the correct account being grabbed with the get_account().
Test passed!

=====

I moved forward in my research on why my run_flashloan.py wasn't working.
I added `"gas_limit": 1200000, "allow_revert": True}` to the weth.transfer function, and the problem slightly moved forward.
Now, the transaction goes through

```
Running 'scripts/run_flashloan.py::main'...
0x4a8e4183709bb59E0807D64E46cFe7747479d371
Getting the flashloan contract for ya!
Giving some of your WETH away to the contract, for gas.
Transaction sent: 0x2d82daed0a0c94511bd1b864c43a523a840e5717f5b4bd2e9b5dc4e671654ba5
  Gas price: 2.500000007 gwei   Gas limit: 1200000   Nonce: 27
  WethInterface.transfer confirmed (reverted)   Block: 32412383   Gas used: 24327 (2.03%)

  File "/usr/local/lib/python3.8/dist-packages/eth_brownie-1.17.2-py3.8.egg/brownie/_cli/run.py", line 50, in main
    return_value, frame = run(
  File "/usr/local/lib/python3.8/dist-packages/eth_brownie-1.17.2-py3.8.egg/brownie/project/scripts.py", line 103, in run
    return_value = f_locals[method_name](*args, **kwargs)
  File "./scripts/run_flashloan.py", line 22, in main
    weth.transfer(
  File "/usr/local/lib/python3.8/dist-packages/eth_brownie-1.17.2-py3.8.egg/brownie/network/contract.py", line 1629, in __call__
    return self.transact(*args)
  File "/usr/local/lib/python3.8/dist-packages/eth_brownie-1.17.2-py3.8.egg/brownie/network/contract.py", line 1502, in transact
    return tx["from"].transfer(
  File "/usr/local/lib/python3.8/dist-packages/eth_brownie-1.17.2-py3.8.egg/brownie/network/account.py", line 682, in transfer
    receipt._raise_if_reverted(exc)
  File "/usr/local/lib/python3.8/dist-packages/eth_brownie-1.17.2-py3.8.egg/brownie/network/transaction.py", line 428, in _raise_if_reverted
    raise exc or ValueError("Execution reverted")
ValueError: Execution reverted
```

Last time, the transaction simply didn't go through.
This time it did, but got reverted. I have to figure out why
https://kovan.etherscan.io/tx/0x26006397462456c95bc98dda78b48f50c72c07ce3e89f22b4fa0f0fb89fa4bf5
I've tried modifying the amounts, I still have 0.186 WETH in my metamask, which is enough to cover the Aave fees, which are 0.09% of the amount borrowed.
