I refilled my testnet account, I had 0.506 WETH in my account
I ran run_flashloan once again and this time the transaction went through, to stop with `flashloan Sequence has incorrect length, expected 2 but got 1`
And my wallet now has only 0.006 WETH !! and no transaction is showing on my wallet that shows where those 0.5 WETH went.
`0x69c235f1e5ffcf0a3a9c8447d580483c4c8521727f1e9396df16ca7d53fce36f` is the transaction hash

brownie run scripts/run_flashloan.py --network kovan
Brownie v1.17.2 - Python development framework for Ethereum

UpdatedVersionProject is the active project.

Running 'scripts/run_flashloan.py::main'...
0x4a8e4183709bb59E0807D64E46cFe7747479d371
Getting the flashloan contract for ya!
Giving some of your WETH away to the contract, for gas.
Transaction sent: 0x69c235f1e5ffcf0a3a9c8447d580483c4c8521727f1e9396df16ca7d53fce36f
Gas price: 2.05 gwei Gas limit: 1200000 Nonce: 40
WethInterface.transfer confirmed Block: 32428086 Gas used: 51759 (4.31%)

Executing flashloan...Be Patient!!
File "/usr/local/lib/python3.8/dist-packages/eth_brownie-1.17.2-py3.8.egg/brownie/\_cli/run.py", line 50, in main
return_value, frame = run(
File "/usr/local/lib/python3.8/dist-packages/eth_brownie-1.17.2-py3.8.egg/brownie/project/scripts.py", line 103, in run
return_value = f_locals[method_name](*args, \*\*kwargs)
File "./scripts/run_flashloan.py", line 28, in main
tx = flashloan.flashloan(
File "/usr/local/lib/python3.8/dist-packages/eth_brownie-1.17.2-py3.8.egg/brownie/network/contract.py", line 1629, in **call**
return self.transact(*args)
File "/usr/local/lib/python3.8/dist-packages/eth_brownie-1.17.2-py3.8.egg/brownie/network/contract.py", line 1512, in transact
data=self.encode_input(\*args),
File "/usr/local/lib/python3.8/dist-packages/eth_brownie-1.17.2-py3.8.egg/brownie/network/contract.py", line 1547, in encode_input
data = format_input(self.abi, args)
File "/usr/local/lib/python3.8/dist-packages/eth_brownie-1.17.2-py3.8.egg/brownie/convert/normalize.py", line 20, in format_input
raise type(e)(f"{abi['name']} {e}") from None
ValueError: flashloan Sequence has incorrect length, expected 2 but got 1

My problem is, those 0.5 WETH correspond to
weth.transfer(
flashloan,
"0.5 ether",
{"from": accountCaller, "gas_limit": 1200000, "allow_revert": True},
) # borrow 0.5ETH in flashloan
which is a big problem !! I'm supposed to borrow 0.5 ETH, not give my WETH away.
I'm fairly confused.
I've tried running deploy.py again to check the rest of my scripts and I had a message error :

Brownie v1.17.2 - Python development framework for Ethereum

UpdatedVersionProject is the active project.

Running 'scripts/deploy.py::main'...
0x4a8e4183709bb59E0807D64E46cFe7747479d371
Transaction sent: 0x9e471b5377768d12a4430919717ce43cb8f3f9987571281f9bd59a6c0e717444
Gas price: 2.05 gwei Gas limit: 1191351 Nonce: 41
File "/usr/local/lib/python3.8/dist-packages/eth_brownie-1.17.2-py3.8.egg/brownie/\_cli/run.py", line 50, in main
return_value, frame = run(
File "/usr/local/lib/python3.8/dist-packages/eth_brownie-1.17.2-py3.8.egg/brownie/project/scripts.py", line 103, in run
return_value = f_locals[method_name](\*args, \*\*kwargs)
File "./scripts/deploy.py", line 6, in main
deploy_flashloan()
File "./scripts/deploy.py", line 11, in deploy_flashloan
flashloan = Flashloan_logic.deploy(
File "/usr/local/lib/python3.8/dist-packages/eth_brownie-1.17.2-py3.8.egg/brownie/network/contract.py", line 528, in **call**
return tx["from"].deploy(
File "/usr/local/lib/python3.8/dist-packages/eth_brownie-1.17.2-py3.8.egg/brownie/network/account.py", line 510, in deploy
receipt, exc = self.\_make_transaction(
File "/usr/local/lib/python3.8/dist-packages/eth_brownie-1.17.2-py3.8.egg/brownie/network/account.py", line 776, in \_make_transaction
receipt = self.\_await_confirmation(receipt, required_confs, gas_strategy, gas_iter)
File "/usr/local/lib/python3.8/dist-packages/eth_brownie-1.17.2-py3.8.egg/brownie/network/account.py", line 818, in \_await_confirmation
raise TransactionError(f"Tx dropped without known replacement: {receipt.txid}")
TransactionError: Tx dropped without known replacement: 0x9e471b5377768d12a4430919717ce43cb8f3f9987571281f9bd59a6c0e717444

I've tried modifying my contract, I noticed the constructor wasn't right after the opening of the contract, so I put it there, and commented out the elements inside the constructor.

The project compiled successfully and another version of the contract was deployed.

Now I want to check my run_flashloan script again and see if there is anything I wrote the wrong way.

Ok I think I understand what's going on, I funded my contract (now not reachable) with 0.5WETH in order for the contract to interact with Aave. and then the Aave transaction failed because I did not indicate an amount of assets to flashloan

aaand now I have new error, the contract did take my WETH, but the transaction reverted :

brownie run scripts/run_flashloan.py --network kovan
Brownie v1.17.2 - Python development framework for Ethereum

UpdatedVersionProject is the active project.

Running 'scripts/run_flashloan.py::main'...
0x4a8e4183709bb59E0807D64E46cFe7747479d371
Getting the flashloan contract for ya!
Giving some of your WETH away to the contract, for gas.
Transaction sent: 0x9017bde27ebeabc4b7f3956f27ae726a062230ebe8b89b7b0b9fdae7d9e4f73f
Gas price: 2.060000007 gwei Gas limit: 1200000 Nonce: 50
WethInterface.transfer confirmed Block: 32430966 Gas used: 34647 (2.89%)

Executing flashloan...Be Patient!!
File "/usr/local/lib/python3.8/dist-packages/eth_brownie-1.17.2-py3.8.egg/brownie/\_cli/run.py", line 50, in main
return_value, frame = run(
File "/usr/local/lib/python3.8/dist-packages/eth_brownie-1.17.2-py3.8.egg/brownie/project/scripts.py", line 103, in run
return_value = f_locals[method_name](*args, \*\*kwargs)
File "./scripts/run_flashloan.py", line 28, in main
tx = flashloan.flashloan(
File "/usr/local/lib/python3.8/dist-packages/eth_brownie-1.17.2-py3.8.egg/brownie/network/contract.py", line 1629, in **call**
return self.transact(*args)
File "/usr/local/lib/python3.8/dist-packages/eth_brownie-1.17.2-py3.8.egg/brownie/network/contract.py", line 1512, in transact
data=self.encode_input(\*args),
File "/usr/local/lib/python3.8/dist-packages/eth_brownie-1.17.2-py3.8.egg/brownie/network/contract.py", line 1547, in encode_input
data = format_input(self.abi, args)
File "/usr/local/lib/python3.8/dist-packages/eth_brownie-1.17.2-py3.8.egg/brownie/convert/normalize.py", line 20, in format_input
raise type(e)(f"{abi['name']} {e}") from None
TypeError: flashloan '0xd0A1E359811322d97991E03f863a0C30C2cF029C' - Expected list or tuple, got Contract
